Allow specifying cluster_ca as unencoded PEM
Typositoire/concourse-helm3-resource pull request #40
Opened 2020-11-04 15:26 UTC by vixus0

Try decoding value as Base64 and fallback to treating value as the
unencoded PEM.

Closes #39

2020-11-04 15:29 UTC, Typositoire requested changes

2020-11-04 15:29 UTC, Typositoire commented on assets/common.sh
> +        fi
I think you didn't mean to put a `fi` there ?

2020-11-04 15:34 UTC, vixus0 commented on assets/common.sh
> +        fi
Ha oops, fixed :)

2020-11-04 17:04 UTC, Typositoire commented
This will be merged and available as latest within 10-20 minutes (Pray the docker hub gods!)

Then it'll be tagged as 1.13.0 soon after. ETA 30 minutes to be in Docker Hub

2020-11-04 17:05 UTC, merged

2020-11-06 10:38 UTC, vixus0 commented
@Typositoire thank you for the speedy turnaround! :)