add gcloud auth
Typositoire/concourse-helm3-resource pull request #58
Opened 2021-06-01 11:18 UTC by shashankkoppar

2021-06-01 12:58 UTC, Typositoire requested changes
We'll also need to bump the version to `1.17.0`

2021-06-01 12:58 UTC, Typositoire commented on README.md
> +-   `gcloud_cluster_auth`: _Optional._ Set to true to use gcloud service account file for kubernetes cluster authentication.
Please make this a separated section just like Digital Ocean.

2021-06-01 12:58 UTC, Typositoire commented on assets/common.sh
>      setup_doctl $1 $2
I'm sure there's a better way to check for this now that we have gcloud, DO and normal. If you feel like you can fix this go ahead otherwise I'll try to figure out something before merging.

2021-06-01 12:58 UTC, Typositoire commented on README.md
> +    gcloud_service_account_key_file: _plain service account json file_
I'd like this to be able to be a file path and check if first the value of `gcloud_service_account_key` is a file then read it, if not assume it's the content then write it to disk like you're doing now.

2021-06-01 12:58 UTC, Typositoire commented on assets/common.sh
> +  kubectl version
Why ?

2021-06-01 12:58 UTC, Typositoire commented on Dockerfile
> +RUN curl -sSL https://sdk.cloud.google.com | bash
Is there a way to lock a version here? Less surprises in the future.

2021-06-03 13:58 UTC, shashankkoppar commented on assets/common.sh
>      setup_doctl $1 $2
Sure yeah, maybe i can check if we can do this with a switch loop

2021-06-03 13:59 UTC, shashankkoppar commented on assets/common.sh
> +  kubectl version
this is how we will be able to set kubectl context using gcloud

2021-06-03 14:00 UTC, shashankkoppar commented on Dockerfile
> +RUN curl -sSL https://sdk.cloud.google.com | bash
Yes, let me check! indeed using specifc version is better

2021-06-03 14:01 UTC, shashankkoppar commented on README.md
> +    gcloud_service_account_key_file: _plain service account json file_
Yes sounds good! will make the changes

2021-06-03 14:03 UTC, Typositoire commented on assets/common.sh
>      setup_doctl $1 $2
Sure let's give this a try.

2021-06-03 14:13 UTC, Typositoire commented on assets/common.sh
> +  kubectl version
I mean the `kubectl version` :P

2021-06-03 15:52 UTC, shashankkoppar commented on assets/common.sh
> +  kubectl version
ah lol just to confirm if kubectl is working fine. can remove it 😄😄

2021-06-03 20:52 UTC, shashankkoppar commented on assets/common.sh
>      setup_doctl $1 $2
switch case seems not so feasible here, but we can improve if condition itself, will commit. u can check!

2021-06-03 21:04 UTC, shashankkoppar commented
```
selected worker: concourseci-worker-1
Initializing kubectl access using gcloud service account file
Activated service account credentials for: [concourse@iam.gserviceaccount.com]
Updated property [core/account].
Updated property [core/project].
Fetching cluster endpoint and auth data.
kubeconfig entry generated for test.
Initializing helm...
```

this is how it looks in console output, have tested with concourse pipeline, works fine.

2021-06-03 21:05 UTC, shashankkoppar commented on Dockerfile
> +RUN curl -sSL https://sdk.cloud.google.com | bash
fixed it latest commit :)

2021-06-03 21:05 UTC, shashankkoppar commented on assets/common.sh
> +  kubectl version
removed this! :D

2021-06-03 21:05 UTC, shashankkoppar commented on README.md
> +    gcloud_service_account_key_file: _plain service account json file_
have done changes, please check in recent commit

2021-06-03 21:06 UTC, shashankkoppar commented on README.md
> +-   `gcloud_cluster_auth`: _Optional._ Set to true to use gcloud service account file for kubernetes cluster authentication.
updated it separate as Digitial ocean!

2021-06-03 21:36 UTC, Typositoire requested changes
Some small changes left but this looks good!

2021-06-03 21:36 UTC, Typositoire commented on README.md
> +-   `gcloud_service_account_key_file`: _Optional_ Manadatory if gcloud_cluster_auth is set to true. Pass gcloud service accon json contents as value or a file path containing service_account json.
```suggestion
-   `gcloud_service_account_key_file`: _Optional_ Manadatory if gcloud_cluster_auth is set to true. Pass gcloud service account json contents as value or a file path containing service_account json.
```

2021-06-03 21:36 UTC, Typositoire commented on assets/common.sh
> +    fi
```suggestion
  elif [ "$gcloud_cluster_auth" = "true" ]; then
      echo "Initializing kubectl access using gcloud service account file"
      setup_gcp_kubernetes $1 $2
  else
    echo "Initializing kubectl using certificates"
    setup_kubernetes $1 $2
  fi
```

2021-06-04 09:41 UTC, shashankkoppar commented on assets/common.sh
> +    fi
my bad, yes updated :)

2021-06-04 09:41 UTC, shashankkoppar commented on README.md
> +-   `gcloud_service_account_key_file`: _Optional_ Manadatory if gcloud_cluster_auth is set to true. Pass gcloud service accon json contents as value or a file path containing service_account json.
fixed the typo :D

2021-06-04 23:23 UTC, Typositoire commented
I'll merge it as latest and tag it when I have 5 minutes my concourse pipeline for tagging doesn't seem to be working right now xD

2021-06-04 23:23 UTC, Typositoire approved these changes

2021-06-04 23:23 UTC, merged

2021-06-05 04:26 UTC, shashankkoppar commented
Thanks man, appreciate it!