Fixing #72, using helm uninstall instead of helm delete
Typositoire/concourse-helm3-resource pull request #73
Opened 2022-01-18 09:53 UTC by dicksol

2022-01-18 22:05 UTC, Typositoire commented
Concourse: Version bump did not happen. v1.20.0 is the same as v1.20.0

2022-01-19 09:29 UTC, rws-deltares commented
@Typositoire, do you expect anything from my side to perform the merge?

2022-01-19 09:33 UTC, dicksol commented
@Typositoire, do you expect anything from my side to have the code change merged.

2022-01-22 15:29 UTC, Typositoire requested changes
Please bump the minor version also! And sooooo sorry for the delay :(

2022-01-22 15:29 UTC, Typositoire commented on assets/common.sh
> +      helm uninstall --purge "$release" --namespace $namespace
You can remove purge, this is no longer a thing (It was kept when moved from v2)

2022-01-23 19:31 UTC, merged

2022-01-23 19:31 UTC, dicksol commented
@Typositoire, processed your remarked. Please merge if okay. Tx.

2022-01-23 19:31 UTC, dicksol commented
Lovely. Tx.

2022-01-23 19:32 UTC, Typositoire commented
Look for a new image in ~10 minutes. (Concourse is doing his job)

2022-01-23 19:53 UTC, Typositoire commented
https://github.com/Typositoire/concourse-helm3-resource/pkgs/container/concourse-helm3-resource/13693660?tag=v1.21.0

2022-01-23 19:54 UTC, dicksol commented
#71, also solved now.

2022-01-23 20:55 UTC, dicksolrws commented
And using it:
Pulling ghcr.io/typositoire/concourse-helm3-resource@sha256:59a179531c97e066a4527948a1336d535768c7a22e46e7e3f2a9f8220bc0b537...

ghcr.io/typositoire/concourse-helm3-resource@sha256:59a179531c97e066a4527948a1336d535768c7a22e46e7e3f2a9f8220bc0b537: Pulling from typositoire/concourse-helm3-resource