Add delete-namespace option when uninstall
Typositoire/concourse-helm3-resource pull request #78
Opened 2022-03-21 07:59 UTC by ThibaultDelaune-pro

Usually, when I uninstall an Helm release, I delete the namespace afterwards. This option would permit that in a single task.

2022-03-21 15:28 UTC, Typositoire commented
Concourse: Version bump found.

2022-03-25 16:12 UTC, Typositoire requested changes

2022-03-25 16:12 UTC, Typositoire commented on VERSION
> +1.22.2
Please make this a minor bump since it introduces a behavior change.

2022-03-25 16:12 UTC, Typositoire commented on assets/out
> +    logfile="/tmp/log"
I think you're missing a `mkdir -p /tmp` after this line.

2022-03-25 16:12 UTC, Typositoire commented on assets/out
> +    kubectl delete namespaces --ignore-not-found=true "$namespace" | tee "$logfile"
In which case would we ask for delete and the namespace would not exist? I don't think the resource should prevent user error if the namespace it is trying to delete doesn't exist.

2022-03-25 16:18 UTC, Berber31 commented on assets/out
> +    kubectl delete namespaces --ignore-not-found=true "$namespace" | tee "$logfile"
yes, but `--ignore-not-found=true` is bulletproof

2022-03-25 16:22 UTC, Berber31 commented on assets/out
> +    logfile="/tmp/log"
i think already done in [helm_uninstall function](https://github.com/Typositoire/concourse-helm3-resource/blob/494c1af10610c5c4e960723450b1aeffbd98ffc5/assets/out#L253)

2022-03-25 16:24 UTC, Typositoire commented on assets/out
> +    kubectl delete namespaces --ignore-not-found=true "$namespace" | tee "$logfile"
I think using https://concourse-ci.org/try-step.html is more flexible than FORCING the resource to ignore any kind of error. Maybe people wants to error out if the namespace doesn't exist.

2022-03-25 16:27 UTC, Typositoire commented on assets/out
> +    logfile="/tmp/log"
Oh wow ok I didn't realize this was at that place. Then that part should be BEFORE the `echo "$result"`. echo should be the last thing that happens.

2022-03-26 02:00 UTC, ThibaultDelaune-pro commented on VERSION
> +1.22.2
Done!

2022-03-26 02:01 UTC, ThibaultDelaune-pro commented on assets/out
> +    logfile="/tmp/log"
Fixed!

2022-03-26 02:02 UTC, ThibaultDelaune-pro commented on assets/out
> +    kubectl delete namespaces --ignore-not-found=true "$namespace" | tee "$logfile"
> yes, but `--ignore-not-found=true` is bulletproof

This was the idea 😉

2022-03-26 02:03 UTC, ThibaultDelaune-pro commented on assets/out
> +    kubectl delete namespaces --ignore-not-found=true "$namespace" | tee "$logfile"
I removed the param

2022-03-26 15:29 UTC, Typositoire commented
Concourse: Version bump found.

2022-03-28 12:00 UTC, Typositoire requested changes
Fix the version then we're good to go!

2022-03-28 13:52 UTC, ThibaultDelaune-pro commented on VERSION
> +1.23.1
Done!
'hope this will do... 😋

2022-03-28 15:29 UTC, Typositoire commented
Concourse: Version bump found.

2022-03-28 18:37 UTC, Typositoire approved these changes

2022-03-28 18:37 UTC, merged