Wait for Jobs
Typositoire/concourse-helm3-resource pull request #85
Opened 2022-08-01 19:17 UTC by mount986

New parameter to set the --wait-for-jobs flag:
`--wait-for-jobs                if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout`

2022-08-01 19:26 UTC, Typositoire requested changes

2022-08-01 19:26 UTC, Typositoire commented on assets/out
> +    fi
Please replace with `elif`

2022-08-01 19:26 UTC, Typositoire commented
Also bump the minor version in `VERSION` file

2022-08-01 19:27 UTC, Typositoire commented
Concourse: Version bump did not happen. v1.25.0 is the same as v1.25.0

2022-08-01 20:31 UTC, mount986 commented on assets/out
> +    fi
fair enough

2022-08-01 20:32 UTC, Typositoire commented
Concourse: Version bump did not happen. v1.25.0 is the same as v1.25.0

2022-08-01 23:14 UTC, Typositoire commented
Concourse: Version bump found.

2022-08-02 11:12 UTC, Typositoire commented
Concourse: Version bump found.

2022-08-03 13:40 UTC, Typositoire commented
Concourse: Version bump found.

2022-08-03 13:41 UTC, Typositoire approved these changes

2022-08-03 13:41 UTC, merged